INSERT INTO public.locations (name) VALUES ('search_error');
INSERT INTO public.locations (name) VALUES ('United States');
INSERT INTO public.locations (name) VALUES ('United Kingdom');
INSERT INTO public.locations (name) VALUES ('Romania');
INSERT INTO public.locations (name) VALUES ('Argentina');
INSERT INTO public.locations (name) VALUES ('Spain');
INSERT INTO public.locations (name) VALUES ('Philippines');
INSERT INTO public.locations (name) VALUES ('Japan');
INSERT INTO public.locations (name) VALUES ('Australia');
INSERT INTO public.locations (name) VALUES ('Canada');
INSERT INTO public.locations (name) VALUES ('Russia');
INSERT INTO public.locations (name) VALUES ('Poland');
INSERT INTO public.locations (name) VALUES ('Germany');
INSERT INTO public.locations (name) VALUES ('France');
INSERT INTO public.locations (name) VALUES ('Brazil');
INSERT INTO public.locations (name) VALUES ('Cameroon');
INSERT INTO public.locations (name) VALUES ('Norway');
INSERT INTO public.locations (name) VALUES ('Sweden');
INSERT INTO public.locations (name) VALUES ('Netherlands');
INSERT INTO public.locations (name) VALUES ('Colombia');
INSERT INTO public.locations (name) VALUES ('Finland');
INSERT INTO public.locations (name) VALUES ('Italy');
INSERT INTO public.locations (name) VALUES ('India');
INSERT INTO public.locations (name) VALUES ('Estonia');
INSERT INTO public.locations (name) VALUES ('Singapore');
INSERT INTO public.locations (name) VALUES ('Chile');
INSERT INTO public.locations (name) VALUES ('Tunisia');
INSERT INTO public.locations (name) VALUES ('Switzerland');
INSERT INTO public.locations (name) VALUES ('New Zealand');
INSERT INTO public.locations (name) VALUES ('Belgium');
INSERT INTO public.locations (name) VALUES ('Czechia');
INSERT INTO public.locations (name) VALUES ('Taiwan');
INSERT INTO public.locations (name) VALUES ('Portugal');
INSERT INTO public.locations (name) VALUES ('Mexico');
INSERT INTO public.locations (name) VALUES ('Greece');
INSERT INTO public.locations (name) VALUES ('Denmark');
INSERT INTO public.locations (name) VALUES ('Laos');
INSERT INTO public.locations (name) VALUES ('Austria');
INSERT INTO public.locations (name) VALUES ('Venezuela');
INSERT INTO public.locations (name) VALUES ('Israel');
INSERT INTO public.locations (name) VALUES ('South Africa');
INSERT INTO public.locations (name) VALUES ('Ireland');
INSERT INTO public.locations (name) VALUES ('Hungary');
INSERT INTO public.locations (name) VALUES ('China');
INSERT INTO public.locations (name) VALUES ('Malta');
INSERT INTO public.locations (name) VALUES ('Thailand');
INSERT INTO public.locations (name) VALUES ('Malaysia');
INSERT INTO public.locations (name) VALUES ('Uruguay');
INSERT INTO public.locations (name) VALUES ('Iran');
INSERT INTO public.locations (name) VALUES ('Nigeria');
INSERT INTO public.locations (name) VALUES ('Lithuania');
INSERT INTO public.locations (name) VALUES ('Peru');
INSERT INTO public.locations (name) VALUES ('Serbia');
INSERT INTO public.locations (name) VALUES ('Bulgaria');
INSERT INTO public.locations (name) VALUES ('Latvia');
INSERT INTO public.locations (name) VALUES ('Indonesia');
INSERT INTO public.locations (name) VALUES ('Slovenia');
INSERT INTO public.locations (name) VALUES ('Liechtenstein');
INSERT INTO public.locations (name) VALUES ('Grenada');
INSERT INTO public.locations (name) VALUES ('Ukraine');
INSERT INTO public.locations (name) VALUES ('Ecuador');
INSERT INTO public.locations (name) VALUES ('Moldova');
INSERT INTO public.locations (name) VALUES ('Nicaragua');
INSERT INTO public.locations (name) VALUES ('Egypt');
INSERT INTO public.locations (name) VALUES ('Hong Kong');
INSERT INTO public.locations (name) VALUES ('Mauritius');
INSERT INTO public.locations (name) VALUES ('Slovakia');
INSERT INTO public.locations (name) VALUES ('Belarus');
INSERT INTO public.locations (name) VALUES ('South Korea');
INSERT INTO public.locations (name) VALUES ('Turkey');
INSERT INTO public.locations (name) VALUES ('Madagascar');
INSERT INTO public.locations (name) VALUES ('Malawi');
INSERT INTO public.locations (name) VALUES ('Croatia');
INSERT INTO public.locations (name) VALUES ('Palestine');
INSERT INTO public.locations (name) VALUES ('Uzbekistan');
INSERT INTO public.locations (name) VALUES ('Bolivia');
INSERT INTO public.locations (name) VALUES ('United Arab Emirates');
INSERT INTO public.locations (name) VALUES ('Kenya');
INSERT INTO public.locations (name) VALUES ('Vietnam');
INSERT INTO public.locations (name) VALUES ('Costa Rica');
INSERT INTO public.locations (name) VALUES ('Sri Lanka');
INSERT INTO public.locations (name) VALUES ('Myanmar (Burma)');
INSERT INTO public.locations (name) VALUES ('Kyrgyzstan');
INSERT INTO public.locations (name) VALUES ('Iceland');
INSERT INTO public.locations (name) VALUES ('Morocco');
INSERT INTO public.locations (name) VALUES ('Jamaica');
INSERT INTO public.locations (name) VALUES ('Bosnia and Herzegovina');
INSERT INTO public.locations (name) VALUES ('Pakistan');
INSERT INTO public.locations (name) VALUES ('Luxembourg');
INSERT INTO public.locations (name) VALUES ('Paraguay');
INSERT INTO public.locations (name) VALUES ('Bangladesh');
INSERT INTO public.locations (name) VALUES ('Qatar');
INSERT INTO public.locations (name) VALUES ('Zambia');
INSERT INTO public.locations (name) VALUES ('Gibraltar');
INSERT INTO public.locations (name) VALUES ('Dominican Republic');
INSERT INTO public.locations (name) VALUES ('Puerto Rico');
INSERT INTO public.locations (name) VALUES ('Cyprus');
INSERT INTO public.locations (name) VALUES ('Tanzania');
INSERT INTO public.locations (name) VALUES ('Guadeloupe');
INSERT INTO public.locations (name) VALUES ('El Salvador');
INSERT INTO public.locations (name) VALUES ('Panama');
INSERT INTO public.locations (name) VALUES ('Jordan');
INSERT INTO public.locations (name) VALUES ('Reunion');
INSERT INTO public.locations (name) VALUES ('Antarctica');
INSERT INTO public.locations (name) VALUES ('Nepal');
INSERT INTO public.locations (name) VALUES ('Montenegro');
INSERT INTO public.locations (name) VALUES ('Macedonia (FYROM)');
INSERT INTO public.locations (name) VALUES ('Ghana');
INSERT INTO public.locations (name) VALUES ('Cambodia');
INSERT INTO public.locations (name) VALUES ('Mozambique');
INSERT INTO public.locations (name) VALUES ('Timor-Leste');
INSERT INTO public.locations (name) VALUES ('Mali');
INSERT INTO public.locations (name) VALUES ('Uganda');
INSERT INTO public.locations (name) VALUES ('Zimbabwe');
INSERT INTO public.locations (name) VALUES ('Georgia');
INSERT INTO public.locations (name) VALUES ('Albania');
INSERT INTO public.locations (name) VALUES ('Mongolia');
INSERT INTO public.locations (name) VALUES ('Lebanon');