INSERT INTO public.languages (name) VALUES ('null');
INSERT INTO public.languages (name) VALUES ('Ruby');
INSERT INTO public.languages (name) VALUES ('JavaScript');
INSERT INTO public.languages (name) VALUES ('C#');
INSERT INTO public.languages (name) VALUES ('C');
INSERT INTO public.languages (name) VALUES ('SAS');
INSERT INTO public.languages (name) VALUES ('GDB');
INSERT INTO public.languages (name) VALUES ('CMake');
INSERT INTO public.languages (name) VALUES ('Makefile');
INSERT INTO public.languages (name) VALUES ('DIGITAL Command Language');
INSERT INTO public.languages (name) VALUES ('M4');
INSERT INTO public.languages (name) VALUES ('HTML');
INSERT INTO public.languages (name) VALUES ('CLIPS');
INSERT INTO public.languages (name) VALUES ('Shell');
INSERT INTO public.languages (name) VALUES ('Visual Basic');
INSERT INTO public.languages (name) VALUES ('Objective-C');
INSERT INTO public.languages (name) VALUES ('PHP');
INSERT INTO public.languages (name) VALUES ('Pascal');
INSERT INTO public.languages (name) VALUES ('Assembly');
INSERT INTO public.languages (name) VALUES ('Python');
INSERT INTO public.languages (name) VALUES ('C++');
INSERT INTO public.languages (name) VALUES ('TeX');
INSERT INTO public.languages (name) VALUES ('Perl');
INSERT INTO public.languages (name) VALUES ('Module Management System');
INSERT INTO public.languages (name) VALUES ('Batchfile');
INSERT INTO public.languages (name) VALUES ('Roff');
INSERT INTO public.languages (name) VALUES ('Ada');
INSERT INTO public.languages (name) VALUES ('DTrace');
INSERT INTO public.languages (name) VALUES ('CSS');
INSERT INTO public.languages (name) VALUES ('ActionScript');
INSERT INTO public.languages (name) VALUES ('ApacheConf');
INSERT INTO public.languages (name) VALUES ('Ragel');
INSERT INTO public.languages (name) VALUES ('CoffeeScript');
INSERT INTO public.languages (name) VALUES ('Java');
INSERT INTO public.languages (name) VALUES ('Groff');
INSERT INTO public.languages (name) VALUES ('Erlang');
INSERT INTO public.languages (name) VALUES ('Emacs Lisp');
INSERT INTO public.languages (name) VALUES ('Arc');
INSERT INTO public.languages (name) VALUES ('Scheme');
INSERT INTO public.languages (name) VALUES ('Bison');
INSERT INTO public.languages (name) VALUES ('Io');
INSERT INTO public.languages (name) VALUES ('Logos');
INSERT INTO public.languages (name) VALUES ('Ragel in Ruby Host');
INSERT INTO public.languages (name) VALUES ('Vim script');
INSERT INTO public.languages (name) VALUES ('ASP');
INSERT INTO public.languages (name) VALUES ('Common Lisp');
INSERT INTO public.languages (name) VALUES ('Rust');
INSERT INTO public.languages (name) VALUES ('Groovy');
INSERT INTO public.languages (name) VALUES ('OCaml');
INSERT INTO public.languages (name) VALUES ('Tcl');
INSERT INTO public.languages (name) VALUES ('Awk');
INSERT INTO public.languages (name) VALUES ('Lua');
INSERT INTO public.languages (name) VALUES ('PostScript');
INSERT INTO public.languages (name) VALUES ('XSLT');
INSERT INTO public.languages (name) VALUES ('NSIS');
INSERT INTO public.languages (name) VALUES ('IDL');
INSERT INTO public.languages (name) VALUES ('Prolog');
INSERT INTO public.languages (name) VALUES ('Meson');
INSERT INTO public.languages (name) VALUES ('Puppet');
INSERT INTO public.languages (name) VALUES ('LilyPond');
INSERT INTO public.languages (name) VALUES ('Haskell');
INSERT INTO public.languages (name) VALUES ('Gherkin');
INSERT INTO public.languages (name) VALUES ('Jupyter Notebook');
INSERT INTO public.languages (name) VALUES ('PowerShell');
INSERT INTO public.languages (name) VALUES ('AutoHotkey');
INSERT INTO public.languages (name) VALUES ('AppleScript');
INSERT INTO public.languages (name) VALUES ('Perl 6');
INSERT INTO public.languages (name) VALUES ('Nu');
INSERT INTO public.languages (name) VALUES ('Standard ML');
INSERT INTO public.languages (name) VALUES ('Fortran');
INSERT INTO public.languages (name) VALUES ('Smarty');
INSERT INTO public.languages (name) VALUES ('D');
INSERT INTO public.languages (name) VALUES ('R');
INSERT INTO public.languages (name) VALUES ('VHDL');
INSERT INTO public.languages (name) VALUES ('Matlab');
INSERT INTO public.languages (name) VALUES ('Parrot');
INSERT INTO public.languages (name) VALUES ('Racket');
INSERT INTO public.languages (name) VALUES ('Terra');
INSERT INTO public.languages (name) VALUES ('Forth');
INSERT INTO public.languages (name) VALUES ('sed');
INSERT INTO public.languages (name) VALUES ('Smalltalk');
INSERT INTO public.languages (name) VALUES ('Yacc');
INSERT INTO public.languages (name) VALUES ('Lex');
INSERT INTO public.languages (name) VALUES ('Scala');
INSERT INTO public.languages (name) VALUES ('Clojure');
INSERT INTO public.languages (name) VALUES ('XS');
INSERT INTO public.languages (name) VALUES ('SystemVerilog');
INSERT INTO public.languages (name) VALUES ('Frege');
INSERT INTO public.languages (name) VALUES ('REXX');
INSERT INTO public.languages (name) VALUES ('NewLisp');
INSERT INTO public.languages (name) VALUES ('Nginx');
INSERT INTO public.languages (name) VALUES ('TypeScript');
INSERT INTO public.languages (name) VALUES ('QMake');
INSERT INTO public.languages (name) VALUES ('Cuda');
INSERT INTO public.languages (name) VALUES ('Liquid');
INSERT INTO public.languages (name) VALUES ('Gnuplot');
INSERT INTO public.languages (name) VALUES ('QML');
INSERT INTO public.languages (name) VALUES ('Boo');
INSERT INTO public.languages (name) VALUES ('Vala');
INSERT INTO public.languages (name) VALUES ('Processing');
INSERT INTO public.languages (name) VALUES ('eC');
INSERT INTO public.languages (name) VALUES ('Thrift');
INSERT INTO public.languages (name) VALUES ('PLpgSQL');
INSERT INTO public.languages (name) VALUES ('ooc');
INSERT INTO public.languages (name) VALUES ('Go');
INSERT INTO public.languages (name) VALUES ('AngelScript');
INSERT INTO public.languages (name) VALUES ('M');
INSERT INTO public.languages (name) VALUES ('Clean');
INSERT INTO public.languages (name) VALUES ('Nix');
INSERT INTO public.languages (name) VALUES ('Oz');
INSERT INTO public.languages (name) VALUES ('ColdFusion');
INSERT INTO public.languages (name) VALUES ('GLSL');
INSERT INTO public.languages (name) VALUES ('Arduino');
INSERT INTO public.languages (name) VALUES ('Kotlin');
INSERT INTO public.languages (name) VALUES ('E');
INSERT INTO public.languages (name) VALUES ('OpenSCAD');
INSERT INTO public.languages (name) VALUES ('Eiffel');
INSERT INTO public.languages (name) VALUES ('POV-Ray SDL');
INSERT INTO public.languages (name) VALUES ('SourcePawn');
INSERT INTO public.languages (name) VALUES ('Elixir');
INSERT INTO public.languages (name) VALUES ('Verilog');
INSERT INTO public.languages (name) VALUES ('Objective-J');
INSERT INTO public.languages (name) VALUES ('Lasso');
INSERT INTO public.languages (name) VALUES ('Kit');
INSERT INTO public.languages (name) VALUES ('Julia');
INSERT INTO public.languages (name) VALUES ('KiCad Layout');
INSERT INTO public.languages (name) VALUES ('Pike');
INSERT INTO public.languages (name) VALUES ('Factor');
INSERT INTO public.languages (name) VALUES ('COBOL');
INSERT INTO public.languages (name) VALUES ('Dylan');
INSERT INTO public.languages (name) VALUES ('Graphviz (DOT)');
INSERT INTO public.languages (name) VALUES ('Mathematica');
INSERT INTO public.languages (name) VALUES ('Inno Setup');
INSERT INTO public.languages (name) VALUES ('PigLatin');
INSERT INTO public.languages (name) VALUES ('SuperCollider');
INSERT INTO public.languages (name) VALUES ('Rascal');
INSERT INTO public.languages (name) VALUES ('ChucK');
INSERT INTO public.languages (name) VALUES ('Bro');
INSERT INTO public.languages (name) VALUES ('RenderScript');
INSERT INTO public.languages (name) VALUES ('Ioke');
INSERT INTO public.languages (name) VALUES ('Jasmin');
INSERT INTO public.languages (name) VALUES ('Pony');
INSERT INTO public.languages (name) VALUES ('PureBasic');
INSERT INTO public.languages (name) VALUES ('ABAP');
INSERT INTO public.languages (name) VALUES ('LLVM');
INSERT INTO public.languages (name) VALUES ('MAXScript');
INSERT INTO public.languages (name) VALUES ('Smali');
INSERT INTO public.languages (name) VALUES ('Chapel');
INSERT INTO public.languages (name) VALUES ('XProc');
INSERT INTO public.languages (name) VALUES ('Hy');
INSERT INTO public.languages (name) VALUES ('Idris');
INSERT INTO public.languages (name) VALUES ('Swift');
INSERT INTO public.languages (name) VALUES ('Squirrel');
INSERT INTO public.languages (name) VALUES ('LiveScript');
INSERT INTO public.languages (name) VALUES ('Rebol');
INSERT INTO public.languages (name) VALUES ('Cool');
INSERT INTO public.languages (name) VALUES ('J');
INSERT INTO public.languages (name) VALUES ('Self');
INSERT INTO public.languages (name) VALUES ('BlitzBasic');
INSERT INTO public.languages (name) VALUES ('Genie');
INSERT INTO public.languages (name) VALUES ('Dogescript');
INSERT INTO public.languages (name) VALUES ('Game Maker Language');
INSERT INTO public.languages (name) VALUES ('Agda');
INSERT INTO public.languages (name) VALUES ('Apex');
INSERT INTO public.languages (name) VALUES ('Hack');
INSERT INTO public.languages (name) VALUES ('Csound');
INSERT INTO public.languages (name) VALUES ('Ring');
INSERT INTO public.languages (name) VALUES ('Omgrofl');
INSERT INTO public.languages (name) VALUES ('Opa');
INSERT INTO public.languages (name) VALUES ('Fantom');
INSERT INTO public.languages (name) VALUES ('XQuery');
INSERT INTO public.languages (name) VALUES ('Elm');
INSERT INTO public.languages (name) VALUES ('Fancy');
INSERT INTO public.languages (name) VALUES ('PureScript');
INSERT INTO public.languages (name) VALUES ('LSL');
INSERT INTO public.languages (name) VALUES ('Ceylon');
INSERT INTO public.languages (name) VALUES ('Golo');
INSERT INTO public.languages (name) VALUES ('OpenEdge ABL');
INSERT INTO public.languages (name) VALUES ('PLSQL');
INSERT INTO public.languages (name) VALUES ('Dart');
INSERT INTO public.languages (name) VALUES ('Crystal');
INSERT INTO public.languages (name) VALUES ('AutoIt');
INSERT INTO public.languages (name) VALUES ('AGS Script');
INSERT INTO public.languages (name) VALUES ('MoonScript');
INSERT INTO public.languages (name) VALUES ('xBase');
INSERT INTO public.languages (name) VALUES ('Limbo');
INSERT INTO public.languages (name) VALUES ('Brainfuck');
INSERT INTO public.languages (name) VALUES ('LOLCODE');
INSERT INTO public.languages (name) VALUES ('Haxe');
INSERT INTO public.languages (name) VALUES ('Tea');
INSERT INTO public.languages (name) VALUES ('Nemerle');
INSERT INTO public.languages (name) VALUES ('Nim');
INSERT INTO public.languages (name) VALUES ('Nit');
INSERT INTO public.languages (name) VALUES ('Shen');
INSERT INTO public.languages (name) VALUES ('Modula-2');
INSERT INTO public.languages (name) VALUES ('Mercury');
INSERT INTO public.languages (name) VALUES ('APL');
INSERT INTO public.languages (name) VALUES ('SaltStack');
INSERT INTO public.languages (name) VALUES ('GCC Machine Description');
INSERT INTO public.languages (name) VALUES ('SQLPL');
INSERT INTO public.languages (name) VALUES ('Gettext Catalog');
INSERT INTO public.languages (name) VALUES ('Scilab');
INSERT INTO public.languages (name) VALUES ('Objective-C++');
INSERT INTO public.languages (name) VALUES ('PAWN');
INSERT INTO public.languages (name) VALUES ('Protocol Buffer');
INSERT INTO public.languages (name) VALUES ('Red');
INSERT INTO public.languages (name) VALUES ('Component Pascal');
INSERT INTO public.languages (name) VALUES ('F#');
INSERT INTO public.languages (name) VALUES ('FreeMarker');
INSERT INTO public.languages (name) VALUES ('XML');
INSERT INTO public.languages (name) VALUES ('GAP');
INSERT INTO public.languages (name) VALUES ('Coq');
INSERT INTO public.languages (name) VALUES ('Isabelle');
INSERT INTO public.languages (name) VALUES ('Modelica');
INSERT INTO public.languages (name) VALUES ('HLSL');
INSERT INTO public.languages (name) VALUES ('Augeas');
INSERT INTO public.languages (name) VALUES ('AMPL');
INSERT INTO public.languages (name) VALUES ('1C Enterprise');
INSERT INTO public.languages (name) VALUES ('Max');
INSERT INTO public.languages (name) VALUES ('VCL');
INSERT INTO public.languages (name) VALUES ('XC');
INSERT INTO public.languages (name) VALUES ('Myghty');
INSERT INTO public.languages (name) VALUES ('EmberScript');
INSERT INTO public.languages (name) VALUES ('NCL');
INSERT INTO public.languages (name) VALUES ('Gosu');
INSERT INTO public.languages (name) VALUES ('Pure Data');
INSERT INTO public.languages (name) VALUES ('BitBake');
INSERT INTO public.languages (name) VALUES ('Pan');
INSERT INTO public.languages (name) VALUES ('Logtalk');
INSERT INTO public.languages (name) VALUES ('SQL');
INSERT INTO public.languages (name) VALUES ('Stata');
INSERT INTO public.languages (name) VALUES ('HCL');
INSERT INTO public.languages (name) VALUES ('IGOR Pro');
INSERT INTO public.languages (name) VALUES ('RAML');
INSERT INTO public.languages (name) VALUES ('SRecode Template');
INSERT INTO public.languages (name) VALUES ('Vue');
INSERT INTO public.languages (name) VALUES ('TXL');
INSERT INTO public.languages (name) VALUES ('Mirah');
INSERT INTO public.languages (name) VALUES ('RPC');
INSERT INTO public.languages (name) VALUES ('PowerBuilder');
INSERT INTO public.languages (name) VALUES ('Harbour');
INSERT INTO public.languages (name) VALUES ('Turing');
INSERT INTO public.languages (name) VALUES ('Mask');
INSERT INTO public.languages (name) VALUES ('Mako');
INSERT INTO public.languages (name) VALUES ('Eagle');
INSERT INTO public.languages (name) VALUES ('GAMS');
INSERT INTO public.languages (name) VALUES ('FLUX');
INSERT INTO public.languages (name) VALUES ('Csound Score');
INSERT INTO public.languages (name) VALUES ('BlitzMax');
INSERT INTO public.languages (name) VALUES ('Pep8');
INSERT INTO public.languages (name) VALUES ('ANTLR');
INSERT INTO public.languages (name) VALUES ('Slash');
INSERT INTO public.languages (name) VALUES ('ATS');
INSERT INTO public.languages (name) VALUES ('Common Workflow Language');