INSERT INTO public.orgs (name, location, raw_location) VALUES ('haml', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('IoLanguage', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('churchio', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bigcartel', 'United States', 'US');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mootools', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('git-cola', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ruby-rdf', 'Austria', 'The Semantic Web');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sprinkle-tool', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rubinius', 'United States', 'Everywhere');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('aasm', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ruby-git', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cucumber', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('xindong', 'China', 'Shanghai, China');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mephistorb', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('outerbody', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('typus', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('eathena', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('git', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ci-reporter', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sapo', 'Portugal', 'Lisbon, Portugal');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sunspot', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('minimagick', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('caring', 'United States', 'San Mateo, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('group7even', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('spree', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('relevance', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('spellcheck-ko', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('arclanguage', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cappuccino', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('syweb', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('w3gh', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('grails', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pluginaweek', 'United States', 'Boston, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('front-end', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rails-sqlserver', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('qtile', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bndtools', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('phusion', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('neo4jrb', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('chanceagency', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('symengine', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('handlino', 'Taiwan', 'Taiwan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fastladder', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('r-lib', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('c7', 'Sweden', 'Stockholm, Sweden');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('psi-im', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('tidyverse', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('lestrrat-morgue', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('spring', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ActsAsParanoid', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('composite-primary-keys', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('LRDesign', 'United States', 'Pasadena, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('issuu', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('insomniapps', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rubber', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('animoto', 'United States', 'New York, NY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ondevnull', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('DotNetOpenAuth', 'Australia', 'WorldWide');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jruby', 'Laos', 'The Internet');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('OpenAMEE', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('beyondgrep', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('vlc', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('activewarehouse', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('itmat', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('coffee', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('twitter-archive', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('roomorama', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('erector', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('imedo', 'Germany', 'Nürnberg');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rock-core', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('beyondthepath', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('standout', 'Sweden', 'Sweden');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('liquidm', 'Germany', 'Berlin');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('wraith', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Amentra', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ruby', 'Japan', 'Matsue, Japan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('erikhuda', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Rexko', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('grbl', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('myles-archive', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fs', 'Russia', 'Russia, Kazan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('beautify-web', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('paltman-archive', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('modulargaming', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('openquery', 'Australia', 'Brisbane, Australia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Lasanha', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('citiustech', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('p3lim-wow', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('trms', 'United States', 'Saint Paul, MN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rubaidh', 'United Kingdom', 'Edinburgh, Scotland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('caffo-archived', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('xilinus', 'France', 'France');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('drupal', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('nulang', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jekyll', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('IronLanguages', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('galaxycats', 'Germany', 'Cologne / Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ruby-oembed', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fabric', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('TampaRuby', 'United States', 'Tampa Bay, FL, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('factor', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Ruleby', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('lastminutelabs', 'United Kingdom', 'London');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bostonrb', 'United States', 'Boston, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('zendesk', 'United States', 'San Francisco');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('eastmedia', 'United States', 'New York, NY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('motmot', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('glyde', 'United States', 'Palo Alto, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('kudelabs', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cosm', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('FreeRADIUS', 'United States', 'The world');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('activemerchant', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('frugalware', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('activescaffold', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('hst', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('xaop', 'Belgium', 'Belgium');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Compass', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('feed2imap', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('prey', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('kentnl', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('i-dcc', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pandastream', 'United States', 'NEVADA CITY CA, US');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('acunote', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bioruby', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rakudo', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('kete', 'New Zealand', 'New Zealand');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ezwerx', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('10to1', 'Belgium', 'Belgium');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jquery', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jazzband', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('techcrunch', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ksdtech', 'United States', 'Kentfield, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('carrierwaveuploader', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('reddit-archive', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('connectbot', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('exceptional', 'United States', 'San Francsico');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('dryphp', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('drypy', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Shopify', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('typecode', 'United States', 'DUMBO, Brooklyn');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ruport', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('scf', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('meso-unimpressed', 'Germany', 'Frankfurt, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('runtimerevolution', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('h1labs', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Ideas2IT', 'India', 'India');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sparklemotion', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('vim-ruby', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('idvcorp', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('veridit', 'Norway', 'Oslo, Norway');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Perl-Toolchain-Gang', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('python-ottawa', 'Canada', 'Ottawa, Ontario, Canada');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('lojban', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('activenetwork', 'United States', 'Dallas, TX');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('dryruby', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('belighted', 'Belgium', 'Brussels, Belgium');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('discoproject', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cpan-testers', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('prawnpdf', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('northern-bites', 'United States', 'Brunswick, ME');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mojomojo', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('spazproject', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mangos', 'United States', 'US/Europe');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('invisiblelines', 'United Kingdom', 'Norwich, Norfolk, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('RubyMoney', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('integrity', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bindle', 'United States', 'Anchorage, AK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('uzbl', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('nixmc', 'United Kingdom', 'Brighton, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('snsdigitaldevs', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('teliax', 'United States', 'Denver, CO');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('thoughtworks', 'China', 'United States, India, England, China, Australia, Germany, Canada, Brazil');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sqlcipher', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('liquidware', 'United States', 'Boston');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('viddler', 'United States', 'Bethlehem, PA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('itteco', 'Canada', 'Ottawa, Canada');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('springyweb', 'United Kingdom', 'UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pingdomserver', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mitdancetroupe', 'United States', 'Cambridge, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Aissac', 'Romania', 'Cluj-Napoca, Romania');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('notonthehighstreet', 'United Kingdom', 'London');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('vifm', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ogc', 'United States', 'Nashville, TN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('aliter', 'United States', 'Everywhere');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('trailblazer', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('princelab', 'United States', 'Brigham Young University, Provo, Utah');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('symphonycms', 'Laos', 'The Internet');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('roodi', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('hyde', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rubycas', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jiva-technology', 'United Kingdom', 'Bristol, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('densitypop', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('freshout', 'United States', 'Philadelphia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('gensen', 'Hong Kong', 'Hong Kong SAR');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rake-compiler', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('linkingpaths', 'Iceland', 'BIO-KEF');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('intersect', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('lepton-eda', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ku-fpg', 'United States', 'Kansas');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('madebymany', 'United Kingdom', 'London, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('swiftmailer', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('incanter', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('funtoo', 'United States', 'Albuquerque, NM, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Refactr', 'United States', 'Minneapolis, MN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('nbio', 'United States', 'San Francisco');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mworks', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('coxlab', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ella', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('expectedbehavior', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('akka', 'Sweden', 'Uppsala, Sweden');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('signal', 'United States', 'Chicago, IL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('freerange', 'United Kingdom', 'London, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('espace', 'Egypt', 'Alexandria, Egypt');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rotaract', 'Germany', 'Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('lincolnloop', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('chicagoruby', 'United States', 'Chicago, IL USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('denzuko-archive', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('freebsd', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('HollowEarthRadio', 'United States', 'Seattle, Wa');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('3scale', 'United States', 'Barcelona, Spain and San Francisco, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('webpy', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('firebelly', 'United States', 'Chicago');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('aforward-oss', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('obtiva', 'United States', 'Chicago, IL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('twitter4r', 'United States', 'Urbana, IL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('wesabe', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('katalyst', 'Australia', 'Adelaide, Australia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('GMOD', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('studiomobile', 'Russia', 'Saint Petersburg, Russia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('evalEmpire', 'search_error', 'Work Local, Push Global');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mintdigital', 'United States', 'London & NYC');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('zencoder', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('floorplanner', 'Netherlands', 'Rotterdam, The Netherlands');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('batchblue', 'United States', 'Providence, RI');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('openorbit', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('internetarchive', 'United States', 'San Francisco');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('oscurrency', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('chromium', 'United States', 'Mountain View');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('shelfworthy', 'Laos', 'The Internet');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('gnoso', 'United States', 'Greenville, South Carolina');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('wwidea', 'United States', 'Missoula, MT');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('web2py', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('turn-project', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('MettaMedia', 'United States', 'Oakland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('finance-quote', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('boost', 'New Zealand', 'Wellington, New Zealand');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('binaryage', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('blackwinter-attic', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('hercules-team', 'search_error', '#augeas on Freenode');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('aosp-mirror', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('szchkt', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('siliconsalad', 'France', 'Lille, France');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('smtpd', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('streamsend', 'United States', 'Sacramento, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('notmaintained', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('eventmachine', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('songkick', 'United Kingdom', 'London');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('krautcomputing', 'Germany', 'Berlin, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('slick', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('simplificator', 'Switzerland', 'Zurich, Switzerland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rhomobile', 'United States', 'San Jose, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mobomo', 'United States', 'Washington, DC');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('inet-framework', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sevenwire', 'United States', 'Costa Mesa, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('CompuTEK-Industries', 'United States', 'Seattle, Wa');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('monome', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('beanstalkd', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('scribd', 'United States', 'San Francisco, California, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('dholst', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('integrum', 'United States', 'Chandler, AZ');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('kyrug', 'United States', 'Lexington, KY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('elevation', 'United States', 'Costa Mesa, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('redis', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('gree', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('publify', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('patientslikeme', 'United States', 'Cambridge, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('albumidentify', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('xmlrunner', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('avvo', 'United States', 'Seattle, WA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('multiplay', 'United Kingdom', 'United Kingdom');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('LLNL', 'United States', 'Livermore, CA, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ministrycentered', 'United States', 'Carlsbad, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('square-circle-triangle', 'Australia', 'Melbourne, Australia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('nitrogen', 'United States', 'Milwaukee, WI, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('t11e', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cdd', 'United States', 'Burlingame, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('openwfm', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('openyou', 'Australia', 'Worldwide');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('textpattern', 'United States', 'Everywhere');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('expanda', 'Japan', 'Japan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jasmine', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('emacscollective', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mobmewireless', 'India', 'India');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('zero-labs', 'Portugal', 'Lisbon, Portugal');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('brug', 'United Kingdom', 'Bristol');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('trnsfr', 'United States', 'Austin, TX');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('aiaio', 'United States', 'New York, NY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('geokit', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('LunarLogic', 'Poland', 'Al. Krasinskiego 17/3, Krakow, Poland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('3jane', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('crushlovely', 'United States', 'New York');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('trabian', 'United States', 'Broad Ripple, IN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('23', 'Denmark', 'Copenhagen, Denmark');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('clojure-emacs', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('uicoderz', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('intelliants', 'Kyrgyzstan', 'Bishkek, KG');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rubyunworks', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cogenda', 'Singapore', 'Singapore');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('django-denorm', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('NUBIC', 'United States', 'Chicago, IL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('arkfriends', 'Thailand', 'Chiang Mai, Thailand');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('customink', 'United States', 'Fairfax, VA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('flourishlib', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('adhearsion', 'United States', 'Atlanta');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('activeadmin', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('brandleadership', 'Switzerland', 'Steinhausen CH');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('flogic', 'United States', 'Nashville, TN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('lua-alchemy', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bekkopen', 'Norway', 'Oslo, Norway');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mynewsdesk', 'Sweden', 'Stockholm, Sweden');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('thethemefoundry', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('deprecate', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('c42', 'India', 'Bangalore');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ample', 'United States', 'Cincinnati, OH');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('gitextensions', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('amphora', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('wiecklabs', 'United States', 'Dallas, TX');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('10gen', 'United States', 'New York, NY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('NetworkBlockDevice', 'United States', 'The World');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('beautiful-code', 'India', 'Hyderabad, IN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('entryway', 'United States', 'floyd, virginia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('libnifalcon', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('dojobrasilia', 'Brazil', 'Brasilia, Brazil');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('notch8', 'United States', 'San Diego, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ubiety', 'Canada', 'Winnipeg, Manitoba');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('CommsenArchive', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('PythonOptimizers', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('BLC', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('escalopes', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ruby-bdb', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('membase', 'United States', 'Mountain View, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rsolr', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('phpms', 'Brazil', 'Campo Grande - Mato Grosso do Sul - Brasil');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('CruGlobal', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mime-types', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('email-spec', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jetthoughts', 'United States', 'FL, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('netzke', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('showdownjs', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('symphonists', 'United States', 'The Web');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('avatarnewyork', 'United States', 'New York, NY 10013');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('coupa', 'United States', 'San Mateo, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('amanikids', 'Tanzania', 'Moshi, Tanzania');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('zentoo', 'Germany', 'Berlin, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fatfreecrm', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cincinnatirb', 'United States', 'Cincinnati, Ohio');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('yui', 'United States', 'Sunnyvale, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('xtreme', 'Sweden', 'Sweden');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('aptana', 'United States', 'Mountain View, CA  USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('BigBrotherBot', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('edgecase', 'United States', 'Columbus, OH');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('digg', 'United States', 'New York, NY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('PartidoDeInternet', 'Spain', 'Spain');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('railslove', 'Germany', 'Cologne, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('thincloud', 'United States', 'California');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('psychoticmeowArchives', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('citrusbyte', 'United States', 'Los Angeles, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('isitchristmas', 'United States', 'Christmas');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('libharu', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('anahoret', 'Ukraine', 'Ukraine, Donetsk');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('integrallis', 'United States', 'Scottsdale, AZ and Columbus, OH');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('openbabel', 'Laos', 'The Internet');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rack', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('osbridge', 'United States', 'Portland, Oregon');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('99designs', 'Australia', 'Melbourne, Australia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('datamapper', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('votesmart', 'United States', 'Montana, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('openminds', 'Belgium', 'Ghent, Belgium');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('tryphon', 'France', 'France');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pero-ict-solutions', 'Netherlands', 'Oosterwolde (Fr), Nederland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('thoughtbot', 'United States', 'USA & London');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('icalendar', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('opal', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('phpcr', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('p5-shorten', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('varvet', 'Sweden', 'Gothenburg, Sweden');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sophsec', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('xero-gateway', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ccnmtl', 'United States', 'New York, NY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('trac-hacks', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ledger', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fork', 'Germany', 'Juliusstraße 25, 22769 Hamburg');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('austinonrails', 'United States', 'Austin, TX');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('perl-catalyst', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('omnigroup', 'United States', 'Seattle WA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ucsc', 'United States', 'Santa Cruz, California');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('xspond', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('holidays', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('w3c-validators', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('validates-email-format-of', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('HERA-Team', 'United States', 'international');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('urug', 'United States', 'Salt Lake City, UT');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('basecamp', 'United States', 'Chicago, IL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sqlanywhere', 'Canada', 'Waterloo, Canada');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('eyestreet', 'United States', 'Leesburg, Virginia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('python-postgres', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('uservoice', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('metafetish', 'United States', 'Bay Area, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ukservers', 'United Kingdom', 'United Kingdom');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('linuxfrorg', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sevenscale', 'United States', 'Seattle, WA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cirg-up', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('attr-encrypted', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('plexydesk', 'Canada', 'Canda, Montreal');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Decisiv', 'United States', 'Glen Allen, VA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('foodcoops', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('opendefinition', 'Norway', 'Norway');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('PageTwo', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mikamai', 'Italy', 'Milano, MI, Italy');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mrhenry', 'Belgium', 'Belgium');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('railsdog', 'United States', 'New York, NY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('space150', 'United States', 'Minneapolis, MN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('nodejs', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('microformats', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('xomboverlord', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mongodb', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('calagator', 'United States', 'Portland, Oregon');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('hashrocket', 'United States', 'Chicago & Jax Beach, FL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('coshx', 'United States', 'Charlottesville, VA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('EnlightenedPerlOrganisation', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('othermedia', 'United Kingdom', 'London, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('naev', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('protonet', 'United States', 'San Francisco');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ecit', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('msales', 'Germany', 'Karlsruhe, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('neco', 'United States', 'New York');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('machine', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('campaignmonitor', 'Australia', 'Sydney, Australia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('CitizensFoundation', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('junit-team', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('softlayer', 'United States', 'Dallas, TX USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('freshblocks', 'United States', 'Cupertino, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('spanner', 'United Kingdom', 'Lake District, England');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sproutit', 'United States', 'Los Altos, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('harvesthq', 'United States', 'NYC, Minnesota, Montana, Pennsylvania, Texas, Indiana, Michigan, Illinois, New Hampshire, Washington DC, South Carolina, Mayne ');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('feincms', 'United States', 'Earth');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mworks-project', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rubyireland', 'search_error', 'Ireland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('CienegaOrchards', 'United States', 'Paicines, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pronique', 'United States', 'United States');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('groonga', 'Japan', 'Yokohama Japan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ktgit', 'United States', 'Raleigh, NC');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('refreshedinburgh', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('MacSysadmin', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('tricycle', 'Australia', 'Melbourne, AU');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('SparkViewEngine', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('collectd', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('malkier', 'Laos', 'The Internet');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('finsignia', 'United States', 'Urbana, Illinois USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('xboxdrv', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('hyperic', 'United States', 'San Francisco');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jquery-form', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('boochtek', 'United States', 'St. Louis, MO');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('p5-number-fraction', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pinax', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rubytaiwan', 'Taiwan', 'Taiwan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('managedfusion', 'United States', 'Phoenixville, PA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('infochimps-labs', 'United States', 'Austin, TX');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('turingstudio', 'United States', 'Berkeley, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('lookout', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('django-haystack', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('thinkcreate', 'Netherlands', 'Amsterdam, NL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('vubiostat', 'United States', 'Nashville, TN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('spox', 'United States', 'forest');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('MagLev', 'United States', 'Beaverton, Oregon, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('secondrotation', 'United States', 'Boston, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('walware', 'Germany', 'Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('feedjira', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ultraspeed', 'United Kingdom', 'London');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fedora-infra', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('trisignia', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('OpenMage', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('netspective', 'United States', 'Silver Spring, MD');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sirikata', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('brutasse-archive', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rentpath', 'United States', 'Atlanta, GA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('capistrano', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('nedforce', 'Netherlands', 'Netherlands');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('canadadrugs', 'Canada', 'Winnipeg, Manitoba, Canada');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('FeeFighters', 'United States', 'Chicago, IL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('phillycocoa', 'United States', 'Philadelphia, PA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Swirrl', 'United Kingdom', 'UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('DjangoAdminHackers', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('indyrb', 'United States', 'Indianapolis, IN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('watir', 'United States', 'Everywhere');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('libwww-perl', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sinatra', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jezdez-archive', 'Canada', 'The Interweb');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('wasabirabbit', 'United States', 'New York, NY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('atlrug', 'United States', 'Atlanta, GA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('gh-unit', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rails', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mathnet', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('slidekit', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('slideshow-s9', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mobility-fw', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('nodebox', 'Belgium', 'Antwerp, Belgium');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('visfleet', 'New Zealand', 'Auckland, NZ');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('coldhardcode', 'United States', 'Everywhere.');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cucumber-attic', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bekk', 'Norway', 'Oslo, Norway');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('squarefactor', 'United States', 'Orlando, FL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('brightbox', 'United Kingdom', 'Leeds, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('machine-legacy', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('unboxed', 'United Kingdom', 'London');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('debuggable', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('gogaruco', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('brontes3d', 'United States', 'Lexington, MA, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('amedia', 'Norway', 'Oslo, Norway');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('plainblack', 'United States', 'Madison, WI');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rubygems', 'United States', 'GEM_HOME');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('wested', 'United States', 'San Francisco');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('internuity', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Test-More', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('github', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('galdomedia', 'Poland', 'Poznań, Poland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('hexagonit', 'Finland', 'Helsinki, Finland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('chef-boneyard', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('enormego', 'United States', 'New York');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Everteam-Software', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('railsant', 'Hong Kong', 'Hong Kong');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('xisfor', 'United Kingdom', 'Brimingham, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pixelandtonic', 'United States', 'Bend, OR');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('AMOpen', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('br', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('paramiko', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sdruby', 'United States', 'San Diego, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('XLRstats', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('studionow', 'United States', 'Nashville, TN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('FluentNHibernate', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('infochimps-away', 'United States', 'Austin, TX');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pixels-and-bits', 'Chile', 'Los Angeles, Chicago');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('oneclick', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('radiant', 'search_error', 'Right behind you');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('openstates', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ging', 'Spain', 'Madrid, Spain');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('gentoo', 'United States', 'Planet Earth');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pwman3', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('laamella-gad', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('approvals', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('phpmentors-jp', 'Japan', 'Japan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('typhoeus', 'Germany', 'Berlin');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('enkari', 'United States', 'Raleigh, NC');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('twinbit', 'United States', 'Milano');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('kylef-archive', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('imatix', 'United States', 'CET');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('soaexpert', 'Brazil', 'São Paulo, Brasil');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('DustinChilson-Old', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Fingertips', 'Netherlands', 'Amsterdam, the Netherlands');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('serverdensity', 'United Kingdom', 'UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('streetlabs', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('oppian', 'United Kingdom', 'London');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('eclipse', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('piece', 'Japan', 'Osaka, Japan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('vim-perl', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('wojodesign', 'United States', 'Chicago,IL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('3dbyggeri', 'Denmark', 'Copenhagen, Denmark');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Perl-Email-Project', 'Laos', 'the internet');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('soundcloud', 'Germany', 'Berlin, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('tipr', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('openhood', 'Luxembourg', 'Luxembourg');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('freelawproject', 'United States', 'Berkeley, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('keycastr', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('directededge', 'Germany', 'Berlin, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('SelfControlApp', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('innovationfactory', 'Netherlands', 'Amsterdam');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jshub', 'United Kingdom', 'London, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ithemes', 'United States', 'Oklahoma City');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('DigitPaint', 'Netherlands', 'Nijmegen, Netherlands');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('apache', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('recortable', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('westarete', 'United States', 'State College, PA, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('glass-and-print', 'United States', 'Philadelphia, PA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mroonga', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('renorb', 'United States', 'Reno, NV');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('simplabs', 'Germany', 'Munich, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('camptocamp', 'Switzerland', 'Lausanne Switzerland / Chambéry France');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('britannica', 'United States', 'Chicago, IL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('comma-csv', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('codemuseum', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('DatabaseCleaner', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('divio', 'Switzerland', 'Switzerland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fande', 'Brazil', 'Porto Alegre');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('koorb-archive', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('shortcut', 'Norway', 'Norway');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('biopython', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mocra', 'Australia', 'Brisbane, Australia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rapidsms', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('todotxt', 'United States', 'Done');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('liberty', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('socrata-platform', 'United States', 'Seattle, WA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('dwhenry-archive', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ninject', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rocketjump', 'United States', 'Orlando, Florida');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('inventables', 'United States', 'Chicago');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('yaml', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('chef', 'United States', 'Seattle, WA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('facebookarchive', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('erlware-deprecated', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('spiceworks', 'United States', 'Austin, TX');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('netmediagroup', 'United States', 'Salt Lake City, UT');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('lestrrat-p5', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rack-test', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('o2sources', 'France', 'Lyon, France');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('reactioncontrol', 'United States', 'Elgin, IL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('kupferlauncher', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('erlware', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('madrailers', 'United States', 'Madison, WI');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('teragonaudio', 'Sweden', 'Stockholm, Sweden');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('speartail', 'Singapore', 'Singapore');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('flapjack', 'United States', 'A monitoring system near you');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('taiyaki', 'Japan', 'Japan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Gibberlings3', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('antelopeusersgroup', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pac', 'India', 'Bangalore');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('d3designs', 'United States', 'Chattanooga, TN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('amberbit', 'Poland', 'Białystok, Poland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cloudspace', 'United States', 'Orlando, Florida');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sermo', 'United States', 'Cambridge, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mhs', 'United States', 'Grand Rapids, MI');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('mockery', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('couchbase', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('teachus', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('FinalsClub', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fastingrobot', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('neworganizing', 'United States', 'Washington, DC');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('rosedu', 'Romania', 'Bucharest, Romania');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('moonlighters', 'Russia', 'Novosibirsk, Russia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('seattlerb', 'search_error', 'We will light you on fire.');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('libfirm', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('smartlogic', 'United States', 'Baltimore, MD');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('carmen-ruby', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('freecause', 'United States', 'Boston, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('codesprinters', 'Poland', 'Kraków, Poland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('dropio', 'United States', 'Brooklyn, NY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('heroku', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('spreedly', 'United States', 'Everywhere');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('chb', 'United States', 'Boston, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('JNRowe-retired', 'search_error', 'Spooky graveyard, Mistland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('otherinbox', 'United States', 'Austin, Texas');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('datadesk', 'United States', 'Spring Street, Downtown Los Angeles, California, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('celery', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('caelum', 'Brazil', 'Brazil');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('adcloud', 'Germany', 'Cologne, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('NUIM-BCL', 'Ireland', 'Maynooth, Ireland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('osCommerce', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('econsultancy', 'United Kingdom', 'London');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('activelabs', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('foxsoft', 'Australia', 'Tamworth');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('inueni', 'Slovenia', 'Kranj, Slovenia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('flexnode', 'Malaysia', 'Kota Kinabalu');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('django-extensions', 'Paraguay', 'Earth, Milky Way');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('dulwich', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('maintainable', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pineapple-tracker', 'United States', 'Pineapple Heights, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('itransact', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('digitalscientists', 'United States', 'Atlanta, GA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('puzzle', 'Switzerland', 'Bern Switzerland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('middlebury', 'United States', 'Middlebury, Vermont');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('perl-cloud-framework', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('treehouse', 'United States', 'Everywhere');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('lua-nucleo', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('badoo', 'United Kingdom', 'Moscow & London');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sunlightlabs', 'United States', 'Washington, DC');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('agincourt', 'United Kingdom', 'East Midlands, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('newrelic', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('socialvibe', 'United States', 'Los Angeles, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('swareopenly', 'United States', 'San Diego, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('eatingbits', 'Sweden', 'Sweden');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('perl6', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cosmocommerce', 'China', 'Shanghai,China');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('AboutUs', 'United States', 'Portland,Or');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('csinitiative', 'United States', 'based in Portland, Ore.');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('thisismedium', 'United States', 'Chattanooga, TN & Chicago IL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('dmzgroup', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('istrategylabs', 'United States', 'Washington, DC');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('malaria-atlas-project', 'United Kingdom', 'Oxford, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('EntropyZero', 'United States', 'Reston, Virginia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jenkinsci', 'United States', 'Santa Clara, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('newism', 'Australia', 'Newcastle, Australia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('tiddlyweb', 'Laos', 'The Internet');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('wildbit', 'United States', 'Philadelphia, PA, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('dagolden', 'United States', 'New York, NY');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('nws', 'Hungary', 'Hungary');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cosmocode', 'Germany', 'Berlin, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('factorylabs', 'United States', 'Denver, CO');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sanger', 'United Kingdom', 'Cambridge, UK');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fel4', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('masugadesign', 'United States', 'Grand Rapids, MI');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('pinax-archives', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('cloudfakers', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('snepo', 'Australia', 'Sydney, Australia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jackalope', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('TekNoLogic', 'search_error', 'Buy it, use it, break it, fix it, trash it, change it, mail - upgrade it, charge it, pawn it, zoom it, press it, snap it, work ');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('onehub', 'United States', 'Seattle, WA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('railsmachine', 'United States', 'Savannah, GA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('thinkbright', 'Netherlands', 'Utrecht, the Netherlands');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sometwodev', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('3rdpartyeve', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('randi2', 'Germany', 'Heidelberg, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('hatena', 'Japan', 'Kyoto, Japan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('collectiveidea', 'United States', 'Holland, MI');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('facebook', 'United States', 'Menlo Park, California');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('elasticserver', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('the-foundation', 'New Zealand', 'Christchurch, New Zealand');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('phacility', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('easy-designs', 'United States', 'Chattanooga, TN USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('copypastel', 'United States', 'San Francisco');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('clevercss', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('systemsbiology', 'United States', 'Seattle, WA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('LaunchAcademy', 'United States', 'Boston, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('vigetlabs', 'United States', 'Falls Church, VA / Durham, NC / Boulder, CO');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('blosxom-fanatics', 'search_error', 'WWW');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('gdi', 'United States', 'Ann Arbor, MI');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('railsware', 'United States', '679 Titicus Road, North-Salem, New York,  10560-1801');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('wistia', 'United States', 'Cambridge, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('sonatype', 'United States', 'Fulton, MD');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('absperf', 'United States', 'Boulder, CO');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('zmanda', 'United States', 'Sunnyvale, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fireho', 'Brazil', 'Brasil');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('guru-sp', 'Brazil', 'São Paulo - Brazil');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fastmail', 'Australia', 'Melbourne, Australia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('perfectline', 'Estonia', 'Estonia');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Yelp', 'United States', 'San Francisco');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('opendns', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('clusterify', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('engineyard', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ubf', 'Japan', 'Tokyo, Japan / Illinois, USA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('redis-store', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Infinidat', 'Israel', 'Herzliya, Israel');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('OpenCorrelate', 'United States', 'United States');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bluesoft', 'Brazil', 'São Paulo, SP, Brasil');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('libusual', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('alim-foundation', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fabpot-graveyard', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bricoleurs', 'Canada', 'Milky Way Galaxy');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('django-de', 'Germany', 'Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('thumblemonks', 'United States', 'Everywhere; but mostly Chicago-ish');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('plastictrophy', 'United States', 'Santa Cruz, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('slideinc', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('asynchrony', 'United States', 'St. Louis, MO');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('webiest', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('netcompanyno', 'Norway', 'Oslo');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('directi', 'India', 'India');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('webbynode', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bigbinary', 'United States', 'San Francisco, Miami & Pune, India');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('RiptideCloud', 'United States', 'Orlando FL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('northshorenetworks', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('SRUG', 'Poland', 'Gliwice, Poland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('fetchapp', 'United States', 'Johnson City, TN');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('wardencommunity', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bioteam', 'United States', 'Boston, MA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('nosedjango', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('ubilabs', 'Germany', 'Hamburg, Germany');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('assembly', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('gsl', 'United States', 'Tampa, FL');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('thrivesmart', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('scs', 'Switzerland', 'Zürich, Switzerland');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('jointheleague', 'United States', 'San Diego, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('topagentnetwork', 'United States', 'San Francisco, CA');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('perl-ldap', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('freenet', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('interchange', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('Pymol-Scripts', 'Australia', 'worldwide');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('orcasgit', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('memcached', null, '');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('hametsu', 'Japan', 'Akihabara, Tokyo, Japan');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('bestpractical', 'United States', 'The Internet (and Boston, MA USA)');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('voormedia', 'Netherlands', 'The Netherlands');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('astrails', 'Israel', 'Tel Aviv, Israel');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('quackingduck-archive', 'United States', 'null');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('threehv', 'United Kingdom', 'Leeds, England');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('browsermedia', 'United States', 'Bethesda, MD');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('soup', 'Austria', 'Vienna, Austria');
INSERT INTO public.orgs (name, location, raw_location) VALUES ('tekgraveyard', 'United States', 'null');